### ISSUE TITLE
Latest version of Prometheus node exporter named 'dev'

### ISSUE THREAD

**Issue by Bert-R** [loganmarchione/hassos-addons#5]
Hi,

I'm a happy user of your addon, but at the moment, I'm a bit reluctant to update to the latest version, because it's named 'dev' (also see [the code here](https://github.com/loganmarchione/hassos-addons/blob/main/prometheus_node_exporter/config.json#L3)). Wouldn't that cause issues in a subsequent update?

Regards,
Bert

**Comment by loganmarchione** [comment]
Bert,

Nope, shouldn't be an issue. Going forward, you'll just see `dev` and get "rolling" updates of `dev` whenever I push them out.

For more details:

1. I'm not tagging releases of the add-on, so before when I was using version numbers, they were just "made up" anyways (I actually called that out in the changelog [here](https://github.com/loganmarchione/hassos-addons/blob/main/prometheus_node_exporter/CHANGELOG.md#note)). The add-on has always been whatever code is on the master branch at the time. There is no way to "go back" to an older version. I opened #6 for some improvements in the distribution process, but no promises on a timeline there.
1. I switched to `dev` because I started using [this workflow](https://github.com/loganmarchione/hassos-addons/blob/e317d8a67df9aa65e0fb124bc534108a332ae65b/.github/workflows/main.yml#L16) to lint the add-on, which ultimately calls [this line](https://github.com/frenck/action-addon-linter/blob/70677a1657c25b8cc8ef5cd2171dd9cf0ee742d4/src/lint.py#L168), which requires the version to be `dev`. In fact, this is what most of the Home Assistant Community Add-ons do:
* [WireGuard](https://github.com/hassio-addons/addon-wireguard/blob/main/wireguard/config.yaml#L3)
* [Prometheus](https://github.com/hassio-addons/addon-prometheus/blob/main/prometheus/config.yaml#L3)
* [Plex](https://github.com/hassio-addons/addon-plex/blob/main/plex/config.yaml#L3)
* [VSCode](https://github.com/hassio-addons/addon-vscode/blob/main/vscode/config.yaml#L3)
* [Bootstack](https://github.com/hassio-addons/addon-bookstack/blob/main/bookstack/config.yaml#L3)

**Comment by Bert-R** [comment]
Hi,

Although I'm not very familiar with the build and deployment process of add-ons, I believe I understand where the versioning of the other add-ons differ from yours. When I'm not mistaken, the deployment workflow of Wireguard is triggered by publishing the release on GitHub. The [latest Wireguard release on GitHub is v0.7.0](https://github.com/hassio-addons/addon-wireguard/releases), which is identical to the release shown when adding the add-on to Home Assistant.

Your add-on does not have releases on GitHub, so the workflow cannot take that version number to put it inside the container image.

If you would move on with using ``dev``, then we would never be able to see differences between the current and new version of the add-on anymore, because they would both be ``dev``.

Regards,
Bert

**Comment by loganmarchione** [comment]
You are correct about the WireGuard build/deployment process. 

1. The author [tags release 0.7.0](https://github.com/hassio-addons/addon-wireguard/releases/tag/v0.7.0)
2. The workflow runs
3. The workflow publishes [docker container images for 0.7.0](https://github.com/orgs/hassio-addons/packages?repo_name=addon-wireguard)

However, the WireGuard config file [doesn't contain](https://github.com/hassio-addons/addon-wireguard/blob/main/wireguard/config.yaml) the [image option](https://developers.home-assistant.io/docs/add-ons/configuration#add-on-configuration).  This means that even though the image is versioned at 0.7.0, when you install WireGuard, you're not using the pre-built docker container images for 0.7.0 that are published on GHCR, instead, you're building from master.

Compare this to the official MariaDB add-on. It uses the [image](https://github.com/home-assistant/addons/blob/master/mariadb/config.yaml#L15) and [version](https://github.com/home-assistant/addons/blob/master/mariadb/config.yaml#L2) options, which means when you install MariaDB, you're using a pre-built container from GHCR.

You will still see changes to my add-on in the [CHANGELOG](https://github.com/loganmarchione/hassos-addons/blob/main/prometheus_node_exporter/CHANGELOG.md), as well as [commit history](https://github.com/loganmarchione/hassos-addons/commits/main) in the repo.

**Comment by Bert-R** [comment]
We'll indeed see changes, but we'll be upgrading from `dev` to `dev` and thus have no idea what to look for in the change log.

**Comment by loganmarchione** [comment]
Ahh, yes you're right about that. 

My current problem is that this repo is not for a single add-on (unlike the WireGuard add-on). If I create a tag for 0.1.0, it will be for everything in the repo. Right now, that's only Node Exporter, but might change in the future if add more add-ons. 🤔

**Comment by loganmarchione** [comment]
Closing this for now. Unfortunately, there is no way to tag a specific release for a single directory. Right now, the only add-on is Node Exporter, but might change in the future if add more add-ons.

The best way to see changes is to view the [CHANGELOG](https://github.com/loganmarchione/hassos-addons/blob/main/prometheus_node_exporter/CHANGELOG.md), as well as [commit history](https://github.com/loganmarchione/hassos-addons/commits/main) in the repo.

**Comment by Bert-R** [comment]
I'm pretty sure that's not the only issue. Home assistant won't recognize your next update, as the version number hasn't changed.

**Comment by loganmarchione** [comment]
@Bert-R  - You were right. I've reverted back to numbered releases and removed the linting script that I was using.

**Comment by Bert-R** [comment]
It's a pity that you have to do that. Thanks for letting me know. Once the new version is available, I'll update to it.

**Comment by Bert-R** [comment]
@loganmarchione: I just upgraded to 0.2.0. Thanks a lot for all the effort!
I noticed a small glitch: 0.2.0 is not mentioned in the release notes.

**Comment by loganmarchione** [comment]
I just updated the CHANGELOG and README to reflect 0.2.0. Might need to refresh and try again.

**Comment by Bert-R** [comment]
That indeed worked. Thanks!
